const { availableLocales } = require('./availableLocales');
const { extraMcData } = require('./extraMcData');
const { languages } = require('./languages');
const { math } = require('./math');
const { newsCountries } = require('./newsCountries');
const {
  animeCharacterSearchOrderChoices,
  animeDownloadSiteChoices,
  animeSearchOrderChoices,
  animeSearchStatusChoices,
  animeSearchTypeChoices,
  banChoices,
  banTempChoices,
  emitChoices,
  githubRepoSortingTypeChoices,
  guildChannels,
  instagramDownloadTypeChoices,
  mangaSearchOrderChoices,
  mangaSearchStatusChoices,
  mangaSearchTypeChoices,
  musicSearchChoices,
  musicSettingChoices,
  roleModifyPermissionTypeChoices,
  rolePermissionChoices,
  searchSortingChoices,
  serverMuteChoices,
  serverMuteTempChoices,
  slowmodeChoices,
  threadChannels,
  tiktokDownloadTypeChoices,
  timeoutChoices,
  twitterDownloadTypeChoices,
  vtuberStreamSorting,
  vtuberVideoSorting,
  waifuChoices,
  youtubeDownloadTypeChoices,
} = require('./slashCommandOptionChoices');
const { supportedMIMETypes } = require('./supportedMIMETypes');
const { units } = require('./units');
const { vtuberAffiliation } = require('./vtuberData');

module.exports = {
  animeCharacterSearchOrderChoices,
  animeDownloadSiteChoices,
  animeSearchOrderChoices,
  animeSearchStatusChoices,
  animeSearchTypeChoices,
  availableLocales,
  banChoices,
  banTempChoices,
  channelCreateChoices: guildChannels,
  channelType: [...guildChannels, ...threadChannels],
  emitChoices,
  extraMcData,
  githubRepoSortingTypeChoices,
  instagramDownloadTypeChoices,
  languages,
  mangaSearchOrderChoices,
  mangaSearchStatusChoices,
  mangaSearchTypeChoices,
  math,
  musicSearchChoices,
  musicSettingChoices,
  newsCountries,
  roleModifyPermissionTypeChoices,
  rolePermissionChoices,
  searchSortingChoices,
  serverMuteChoices,
  serverMuteTempChoices,
  slowmodeChoices,
  supportedMIMETypes,
  tiktokDownloadTypeChoices,
  timeoutChoices,
  twitterDownloadTypeChoices,
  units,
  vtuberAffiliation,
  vtuberVideoSortingChoices: vtuberVideoSorting,
  vtuberStreamSortingChoices: [...vtuberVideoSorting, ...vtuberStreamSorting],
  waifuChoices,
  youtubeDownloadTypeChoices,
};
