const { extraMcData } = require('./extraMcData');
const { languages } = require('./languages');
const { math } = require('./math');
const { newsCountries } = require('./newsCountries');
const {
  animeCharacterSearchOrderChoices,
  animeSearchOrderChoices,
  animeSearchStatusChoices,
  animeSearchTypeChoices,
  banChoices,
  banTempChoices,
  emitChoices,
  githubRepoSortingTypeChoices,
  guildChannels,
  mangaSearchOrderChoices,
  mangaSearchStatusChoices,
  mangaSearchTypeChoices,
  mdnLocaleChoices,
  musicSearchChoices,
  musicSettingChoices,
  roleModifyPermissionTypeChoices,
  rolePermissionChoices,
  searchSortingChoices,
  serverMuteChoices,
  serverMuteTempChoices,
  slowmodeChoices,
  threadChannels,
  timeoutChoices,
  vtuberStreamSorting,
  vtuberVideoSorting,
  waifuChoices,
} = require('./slashCommandOptionChoices');
const { vtuberAffiliation } = require('./vtuberData');

module.exports = {
  animeCharacterSearchOrderChoices,
  animeSearchOrderChoices,
  animeSearchStatusChoices,
  animeSearchTypeChoices,
  banChoices,
  banTempChoices,
  channelCreateChoices: guildChannels,
  channelType: [...guildChannels, ...threadChannels],
  emitChoices,
  extraMcData,
  githubRepoSortingTypeChoices,
  languages,
  mangaSearchOrderChoices,
  mangaSearchStatusChoices,
  mangaSearchTypeChoices,
  math,
  mdnLocaleChoices,
  musicSearchChoices,
  musicSettingChoices,
  newsCountries,
  roleModifyPermissionTypeChoices,
  rolePermissionChoices,
  searchSortingChoices,
  serverMuteChoices,
  serverMuteTempChoices,
  slowmodeChoices,
  timeoutChoices,
  vtuberAffiliation,
  vtuberVideoSortingChoices: vtuberVideoSorting,
  vtuberStreamSortingChoices: [...vtuberVideoSorting, ...vtuberStreamSorting],
  waifuChoices,
};
