module.exports = {
  ak: 'Twi',
  as: 'Assamese',
  ay: 'Aymara',
  bho: 'Bhojpuri',
  bm: 'Bambara',
  ckb: 'Kurdish (Sorani)',
  doi: 'Dogri',
  dv: 'Dhivehi',
  ee: 'Ewe',
  gn: 'Guarani',
  gom: 'Konkani',
  ilo: 'Ilocano',
  kri: 'Krio',
  lg: 'Luganda',
  ln: 'Lingala',
  lus: 'Mizo',
  mai: 'Maithili',
  'mni-Mtei': 'Meiteilon (Manipuri)',
  nso: 'Sepedi',
  om: 'Oromo',
  or: 'Odia (Oriya)',
  qu: 'Quechua',
  rw: 'Kinyarwanda',
  sa: 'Sanskrit',
  ti: 'Tigrinya',
  tk: 'Turkmen',
  ts: 'Tsonga',
  tt: 'Tatar',
  ug: 'Uyghur',
};
