module.exports = {
  hololive: 'Hololive',
  nijisanji: 'Nijisanji',
  independents: 'Independents',
  '.live': '.LIVE',
  '774inc': '774Inc',
  aogiriHighschool: 'Aogiri Highschool',
  atellerLive: 'Ateller Live',
  axelV: 'Axel-V',
  akioAir: 'AkioAIR',
  aetheria: 'Aetheria',
  chukorara: 'Chukorara',
  cloudHorizon: 'Cloud Horizon',
  elleneFamily: 'Ellene Family',
  emoechi: 'Emoechi',
  guildCq: 'GuildCQ',
  hoshimeguriGakuen: 'Hoshimeguri Gakuen',
  hLive: 'H.Live',
  iridori: 'Iridori',
  idolCorp: 'Idol Corp',
  kamitsubaki: 'KAMITSUBAKI',
  kizunaAiInc: 'Kizuna Ai Inc.',
  kawaiiMusic: 'Kawaii Music',
  kemomimiRefle: 'Kemomimi Refle',
  kemonoFriends: 'Kemono Friends',
  laPecheParty: 'La Peche Party',
  MarblS: 'Marbl_s',
  masquerade: 'Masquerade',
  maha5: 'MAHA5',
  myHoloTV: 'MyHolo TV',
  meridianProject: 'Meridian Project',
  noriPro: 'Nori Pro',
  nijigen: 'NIJIGEN',
  neoPorte: 'Neo-Porte',
  nkShoujo: 'NKShoujo',
  productionKawaii: 'Production Kawaii',
  polygon: 'Polygon',
  phaseConnect: 'Phase Connect',
  pixelaProject: 'Pixela Project',
  prism: 'PRISM',
  proPro: 'Pro Pro',
  pinkPunkPro: 'Pink Punk Pro',
  riotMusic: 'Riot Music',
  reAct: 'ReAct',
  reMemories: 'ReMemories',
  sleepMonster: 'Sleep Monster',
  squareLive: 'Square Live',
  snacknili: 'Snacknili',
  shinsougumi: 'Shinsougumi',
  tsunderia: 'Tsunderia',
  twitchIndependents: 'Twitch Independents',
  theBox: 'The Box',
  unrealNightGirls: 'Unreal Night Girls',
  vDimensionCreators: 'V Dimension.Creators',
  voiceOre: 'VOICE-ORE',
  vivid: 'VIVID',
  voms: 'VOMS',
  vShojo: 'VShojo',
  vSpo: 'VSpo',
  vReverie: 'VReverie',
  wactor: 'WACTOR',
  wakEntertainment: 'WAK Entertainment',
  xEncount: "X Enc'ount",
  xtremeDeepFieldProject: 'Xtreme Deep Field Project',
  yuniCreate: 'Yuni Create',
  yumeReality: 'Yume Reality',
};
